export const MEMBERS = [
  { id: "A1",  name: "Anthony Lam",   role: "上市審計師",           company: "Privatco CPA Limited",                    category: "A" },
  { id: "A2",  name: "Paul Hung",     role: "估值師",               company: "AP Appraisal Limited",                    category: "A" },
  { id: "A3",  name: "Bun Chan",      role: "上市律師",             company: "Bun Chan Lawyers",                        category: "A" },
  { id: "A4",  name: "Amie Wong",     role: "僱傭公司 (外勞及外傭)", company: "美亞海外僱傭公司",                         category: "A" },
  { id: "A5",  name: "Christy Chan",  role: "政府資助顧問",         company: "Youth Star-up (HK)",                      category: "A" },
  { id: "A6",  name: "Edmund Ho",     role: "滅蟲服務",             company: "衍基蟲控有限公司",                        category: "A" },
  { id: "A7",  name: "Paul Chan",     role: "人力資源顧問",         company: "Collabyrinth Partners Limited",            category: "A" },
  { id: "A8",  name: "Ben Shum",      role: "稅務顧問",             company: "Sforzando Consultant Ltd",                category: "A" },
  { id: "A9",  name: "YY Li",         role: "中小企會計",           company: "WOS CPA Limited",                         category: "A" },
  { id: "A10", name: "Douglas Li",    role: "收購合併律師",         company: "Douglas & Co.",                           category: "A" },
  { id: "A11", name: "Daniel Kuan",   role: "大律師 (民事訴訟)",    company: "Kuan, Hong Kin Daniel (Barrister-at-law)", category: "A" },
  { id: "A12", name: "Jonathan Hung", role: "人力資源 - 創科招聘",  company: "Pinnacle Lead Consulting Limited",         category: "A" },
  { id: "A13", name: "Jo Wong",       role: "財經印刷",             company: "Elegance Financial Communications",        category: "A" },
  { id: "B1",  name: "Dan Yeung",     role: "國際匯款",             company: "三昇聯匯找換行",                          category: "B" },
  { id: "B2",  name: "Freddy Tse",    role: "僱員福利策劃",         company: "FWD Life",                                category: "B" },
  { id: "B3",  name: "Kat Mung",      role: "英國及杜拜物業",       company: "SHLondon Property",                       category: "B" },
  { id: "B4",  name: "Ralph Tam",     role: "個人保險",             company: "FWD Life",                                category: "B" },
  { id: "B5",  name: "Winkie Shuen",  role: "財經資訊服務",         company: "TQ.net",                                  category: "B" },
  { id: "B6",  name: "Tita Li",       role: "證券投資",             company: "富昌金融",                                category: "B" },
  { id: "B7",  name: "Jiminy Wong",   role: "銀行開戶及貸款顧問",   company: "INNIX Consultant Limited",                category: "B" },
  { id: "B8",  name: "Jax Yu",        role: "信託顧問",             company: "Jadeite Family Office",                   category: "B" },
  { id: "C1",  name: "Alvin Kwong",   role: "農地管理",             company: "Magic Season Limited",                    category: "C" },
  { id: "C2",  name: "Nigo Chan",     role: "住宅裝修工程",         company: "大山公司",                                category: "C" },
  { id: "C3",  name: "Cherry Li",     role: "清拆工程",             company: "祥晉工程集團有限公司",                    category: "C" },
  { id: "D1",  name: "Ken Wong",      role: "餐飲供應鏈系統服務",   company: "Prophecy HK",                             category: "D" },
  { id: "D2",  name: "Elaine Wong",   role: "網站用戶體驗專家",     company: "wwwUxer",                                 category: "D" },
  { id: "D3",  name: "Kelvin Lo",     role: "Web3區塊鏈項目供應商", company: "UD Blockchain",                           category: "D" },
  { id: "D4",  name: "Keith Liu",     role: "用戶界面及平面設計",   company: "Fever Studio",                            category: "D" },
  { id: "D5",  name: "Kam Cheung",    role: "人工智慧及數碼轉型",   company: "Reunite Limited",                         category: "D" },
  { id: "E1",  name: "Harris Shim",   role: "醫美診所",             company: "Dr Timeless Medical Ltd",                 category: "E" },
  { id: "E2",  name: "Cat Chan",      role: "日間手術中心",         company: "HC Medical 康智醫療",                     category: "E" },
  { id: "E3",  name: "Kenson Lau",    role: "物理治療中心",         company: "Aura Physiotherapy & Wellness",           category: "E" },
  { id: "E4",  name: "Bowie Sin",     role: "住院手術醫生 (骨科)",  company: "Joys Medical Centre",                     category: "E" },
  { id: "G1",  name: "Chris Law",     role: "連鎖中式酒家",         company: "德聲飲食集團",                            category: "G" },
  { id: "G2",  name: "Taite Poon",    role: "米油廠",               company: "金滿堂食品有限公司",                      category: "G" },
  { id: "G3",  name: "Dickson Kwok",  role: "凍肉批發及零售",       company: "香港食肉獸",                              category: "G" },
  { id: "G4",  name: "Karen Chan",    role: "特色調酒供應",         company: "Dea Group Limited",                       category: "G" },
  { id: "G5",  name: "Elaine Man",    role: "手工堅果批發及零售",   company: "兩蚊夫妻",                                category: "G" },
  { id: "H1",  name: "Dennis Ho",     role: "音樂教育統籌及管理",   company: "TUT Music",                               category: "H" },
  { id: "H2",  name: "Niki Tse",      role: "中英數兒童教育",       company: "Child World Education",                   category: "H" },
  { id: "H3",  name: "Mandy Pang",    role: "兒童遊戲及沙盤治療",   company: "T&T Consultant Limited",                  category: "H" },
  { id: "I1",  name: "Eric Chan",     role: "禮品及贈品",           company: "Spirit (Asia Pacific)",                   category: "I" },
  { id: "I2",  name: "Mandy Law",     role: "公關及活動策劃",       company: "Radiance PR & Martech",                   category: "I" },
  { id: "I3",  name: "Wade Wong",     role: "商業攝影",             company: "WOOOK Production",                        category: "I" },
  { id: "I4",  name: "Ken Cheung",    role: "派對宴會統籌",         company: "Milk House Beauty",                       category: "I" },
  { id: "J1",  name: "Lydia Cheung",  role: "髮型設計",             company: "Moon Salon",                              category: "J" },
  { id: "J2",  name: "Louis Leung",   role: "西裝訂製",             company: "Etude Lotus",                             category: "J" },
];

export const CATEGORY_LABELS = {
  A: "企業服務", B: "金融服務", C: "建築工程", D: "資訊科技",
  E: "醫療保健", F: "製造分銷", G: "餐飲食品", H: "教育",
  I: "市場推廣", J: "生活品味",
};

export const CATEGORY_COLORS = {
  A: "#e74c3c", B: "#e67e22", C: "#f1c40f", D: "#2ecc71",
  E: "#1abc9c", F: "#3498db", G: "#9b59b6", H: "#e91e63",
  I: "#00bcd4", J: "#795548",
};

export const REFERRAL_TYPES = [
  "尋找客戶 / 業務合作",
  "尋找供應商 / 服務提供者",
  "尋找投資者",
  "尋找合作夥伴",
  "尋找人才 / 招募",
  "介紹予特定行業聯絡人",
  "其他",
];

export const TYPE_COLORS = {
  "尋找客戶 / 業務合作":    "#1a4a7a",
  "尋找供應商 / 服務提供者": "#2d6a4f",
  "尋找投資者":             "#7b3f00",
  "尋找合作夥伴":           "#4a1a7a",
  "尋找人才 / 招募":        "#7a1a3a",
  "介紹予特定行業聯絡人":   "#1a5f7a",
  "其他":                   "#555",
};
